// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package dependecies

import (
	"github.com/bilhaqi28/gin-product-service/config"
	"github.com/bilhaqi28/gin-product-service/repository"
	"github.com/bilhaqi28/gin-product-service/service"
)

// Injectors from injector.go:

func InitializedServer() service.ServiceProduct {
	repositoryProduct := repository.NewRepositoryProduct()
	db := config.NewDB()
	serviceProduct := service.NewServiceProduct(repositoryProduct, db)
	return serviceProduct
}
